name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Lint & Build
        working-directory: ./backend
        run: |
          npm run lint
          npm run build