name: Lint

on: pull_request
jobs: 
  eslint: 
    name: "Prepare action"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        uses: Krizzu/eslint-check-action@v1.1.0
        with: 
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintFiles: backend/src
          eslintConfig: backend/.eslintrc.json
          eslintExt: "ts, tsx"

